markdown: kramdown
url: ''
baseurl: null
title: Amazing grace
description: Spread  the fragrance of Christ  love
site-image: /assets/images/meta.png
site-keywords: 'Site, Template, Theme'
favicon-url: 'null'
heroimage: /assets/images/meta.png
email: amazinggrace@gmail.com
facebook_username: Amazing grace
twitter_username: Amazing grace
instagram_username: Amazing grace
linkedin_username: Amazing grace
github_username: Amazing grace
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: null
disqus-shortname: Amazing grace
author-name: Amazing grace
author-image: >-
  https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-about: >-
  A good gardener anticipates the blooming time of each plant and plant them
  wisely to get the desired effect ,which enhance, contrast or blend with the
  beauty of other plants. The joy of watching each plant blooming at various
  times is distinctive than all the flowering plants bloom at once and withers
  together. 


  Similarly, Each one has a different calling and and are expected to bloom at
  different timings. Also they are prepared differently for the task they are
  assigned to. So the waiting time is worth as long as you have the hope in the
  Lord. He who promised will make it happen at His time. We all know the life
  stages of a butterfly. Until the last stage appears, the same being is not
  seen beautiful or worthy. Rejoice when Lord's work is seen in others life and
  wait patiently for your time.
author-url: 'https://github.com/thedevslot'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
